# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: semaphore-api
version: 0.1.0
readme: README.md
authors:
  - Vitex Software (github.com/VitexSoftware)
description: Ansible modules for Ansible Semaphore API 
license_file: LICENSE
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - semaphore
  - api-client
repository: https://github.com/VitexSoftware/semaphore-api
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/ansible-collections/community.semaphore-api
issues: https://github.com/ansible-collections/community.semaphore-api/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
dependencies: {'git@github.com:VitexSoftware/libpython-semaphore-client.git': 'devel'}
